### ISSUE TITLE
Return variable with specified type

### ISSUE THREAD

**Issue by piotrzajac** [ObjectivityLtd/Cake.Deploy.Variables#6]
It would be nice to have an option of returning ReleaseVariable with a specified type, e.g.:
```csharp
bool isLocal = ReleaseVariable<bool>("IsLocal");
```
or 
```csharp
bool isLocal = ReleaseVariable("IsLocal", typeof(bool));
```

It could be narrowed down to simple types e.g. only these implementing IConvertible.

**Comment by januszmarcinik** [comment]
#7
